name: Deploy Flutter Web to AWS EC2 with Nginx

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - closed
    branches:
      - main

jobs:
  deploy:
    if: github.event.pull_request.merged == true || github.event_name == 'push'
    runs-on: ubuntu-latest

    steps:
      # 1. 리포지토리 체크아웃
      - name: Checkout Repository
        uses: actions/checkout@v4

      # 2. Flutter 설치
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: '3.24.5'

      # 3. 의존성 설치
      - name: Install Dependencies
        run: flutter pub get

      # 4. Flutter Web 빌드
      - name: Build Flutter Web
        run: flutter build web --web-renderer html

      # 5. EC2에 파일 복사
      - name: Upload Flutter Web to EC2
        uses: appleboy/scp-action@v0.1.8
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          source: build/web/
          target: /home/ubuntu/flutter-web/build/web/

      # 6. Nginx 설정 및 재시작
      - name: Configure Nginx and Restart
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          port: 22
          script: |
            echo "Updating and Installing Dependencies..."
            sudo apt update
            sudo apt install -y nginx

            echo "Configuring Nginx for Flutter Web..."
            sudo bash -c "cat > /etc/nginx/sites-available/default" << 'CONFIG'
            server {
                listen 80;
                listen [::]:80;

                root /home/ubuntu/flutter-web/build/web;
                index index.html;

                location / {
                    try_files \$uri /index.html;
                }
            }
            EOF 

            echo "Restarting Nginx..."
            sudo systemctl restart nginx
